spring:
  profiles:
    active: prod
    include:
      - db
      - profile

  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

server:
  port: 8082
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: secret
    protocol: TLS
    enabled: true
  http2:
    enabled: true
